# Generated by Django 6.0.2 on 2026-02-13 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='ニックネーム')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='自己紹介')),
                ('affiliation', models.CharField(blank=True, max_length=100, verbose_name='所属')),
                ('is_researcher', models.BooleanField(default=False, verbose_name='研究者フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
